### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by pangqingyuan1991** [testwhat/SmaliEx#11]
Can  not run 
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/rh/smaliex/Main : Unsupported major.minor version 52.0
openjdk 7

**Comment by wanam** [comment]
You need Jdk 8.

J2SE 8 = 52 (0x34 hex)
J2SE 7 = 51 (0x33 hex)
J2SE 6.0 = 50 (0x32 hex)
J2SE 5.0 = 49 (0x31 hex)
JDK 1.4 = 48 (0x30 hex)
JDK 1.3 = 47 (0x2F hex)
JDK 1.2 = 46 (0x2E hex)
JDK 1.1 = 45 (0x2D hex)

**Comment by pangqingyuan1991** [comment]
I know that jdk 8 is working.
And I have compiled the source with openjdk7,but still cannot run.

**Comment by wanam** [comment]
"Unsupported major.minor version 52.0" means it's built with jdk8, check your path variable.

**Comment by pangqingyuan1991** [comment]
Oh,Sorry,my fault.
