### ISSUE TITLE
Mipad 2 problem deodex

### ISSUE THREAD

**Issue by ale8530** [testwhat/SmaliEx#16]
I have segnalate this bug-->https://github.com/BurgerZ/jBART/issues/141

Thanks :)

**Comment by testwhat** [comment]
Please provide the odex files and boot.oat.

**Comment by ale8530** [comment]
certainly you can download it here ->https://mega.nz/#!JkhXBSjC!wC7up21QIMNvmccPHfxqyupDNArsZQ3etjbuDs5aL8M

Thanks for your collaboration :)

**Comment by testwhat** [comment]
Is there other odex of app?
boot.oat from the link looks no error.

**Comment by ale8530** [comment]
You can download the ROM from here http://en.miui.com/download-296.html.

We found serious bugs with services.jar, which does not allow the boot.
