### ISSUE TITLE
Update smali/baksmali in oat2dex

### ISSUE THREAD

**Issue by ingbrzy** [testwhat/SmaliEx#21]
Hi.. 

How to update built in smali/baksmali to the latest in oat2dex?

just update /smali branch of this repo and build new oat2dex..?

currently there is 2.0.8 and latest released is 2.1.2... 

thank you

**Comment by mfonville** [comment]
Same request here...

**Comment by testwhat** [comment]
It might not have significant difference. [2.1.2](https://github.com/testwhat/SmaliEx/releases/tag/snapshot-s)

**Comment by mfonville** [comment]
@testwhat thanks!
Also I am hoping that (bak)smali will get an update soon to fix the errors I experience with fugu ( https://github.com/JesusFreke/smali/issues/385 ) and in that case should fix #20
