### ISSUE TITLE
[Android API 24] Unusual output during oat2dex conversion and error during dex2jar conversion

### ISSUE THREAD

**Issue by kasptom** [testwhat/SmaliEx#37]
I was trying to extract from the emulator dex files from files in (interchangeably):
* /system/framework/x86_64
* /system/framework/x86
* /system/framework/arm
* /system/framework/arm64

I've pulled them from the device and then tried to convert boot directory --> .dex using command, e.g:
`[...]$ java -jar ../oat2dex.jar boot x86_64`

I've got x86_64-odex and  x86_64-dex directories but CLI output suggests that it did not succeed in 100%. 
From one of the dex files in *-odex I wanted to get .jar so I've used dex2jar tool.
`[...]$ sh ../dex2jar-2.0/d2j-dex2jar.sh -d toconvert.dex > output_dex2jar.txt `
result:
```
dex2jar toconvert.dex -> ./toconvert-dex2jar.jar
com.googlecode.d2j.DexException: not support version.
 at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:151)
 at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:211)
 at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:104)
 at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
 at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)
```

Above method works for emulators with API 23 but NOT for API 24
I attach output from: java -jar ../oat2dex.jar boot x86_64
[command_output.txt](https://github.com/testwhat/SmaliEx/files/419850/command_output.txt)

Using release version of oat2dex did not succeed at all, so -like it is written in #19- I've obtained oat2dex from sources.
#36 

EDIT: Emulator that I've used:
[emulator_details.txt](https://github.com/testwhat/SmaliEx/files/419865/emulator_details.txt)

**Comment by kasptom** [comment]
#36 #19

**Comment by imknown** [comment]
All operations are doing under `Microsoft Windows 10`:  

0. Create the folder named `'TryDeodex' `(full address may like `D:\TryDeodex`),  
    then put the self-compiled jar `oat2dex.jar` into the folder.  
    Here is what you said and what I checked out:  
    * https://github.com/testwhat/SmaliEx/issues/36#issuecomment-239366923
1. I copied the folder `/system/framework/`  
    from `system.img` of `Nexus 5X Android 7 DP5 offcial ROM`  
    to the folder `TryDeodex`,  
    and I think you pulled `them` from `virual or real device exist filesystem` maybe okay too;
2. Open terminal and `cd /D D:\TryDeodex`;
3. I used command as:   
   `java -jar oat2dex.jar boot system\framework\arm64`  
	to generate  
   `system\framework\arm64-odex` (full is `D:\TryDeodex\system\framework\arm64-odex`);
4. Get the odex file such as `xxx.odex`, which is `extracted from ROM` or `pulled from virual or real device` via `adb`;
5. Put the file `xxx.odex` in the directory of `'D:\TryDeodex'` noticed above;
5. Try the command:  
    `java -jar oat2dex.jar xxx.odex system\framework\arm64-odex`,
	then you will get `xxx.dex`.
6.Finally use `dex2jar` to get `xxx.jar` file, then try to decompile `xxx.jar`.  
   However, I usually use GUI tools like `bytecode-viewer` on Github  
   to view `java` source code from `xxx.jar` directly (`bytecode-viewer` auto decompiles `xxx.jar`).

I hope these will help you get the source codes. :ghost:

**Comment by kasptom** [comment]
Thanks I will try it and give a feedback if it worked :smiley:

**Comment by kasptom** [comment]
Unfortunately above method does not work for me.
After running `oat2dex` command on Windows 10 I get output that is similar to [https://github.com/testwhat/SmaliEx/files/419850/command_output.txt](url).
I found an image by googling "Nexus 5X Android 7 DP5 offcial ROM" but after extracting the archive I had to use also:
* **sgs2toext4.jar** - to convert **system.img** (output **system.ext4.img**)
* http://www.diskinternals.com/linux-reader/ - to mount the image and read it

I found on the mounted **system.ext4.img** image the directory: 
system\framework\arm64 
and got from it **arm64-odex** using the above **oat2dex** command 

I don't have xxx.odex file. To be precise - file that I want to extract is **framework-classes2.dex** which  is in the generated **arm64-odex**.
On **API 23** I just have to use:
* `java -jar oat2dex.jar boot arm64 `- to get arm64-odex/ and arm64-dex
* `sh ../path/to/d2j-dex2jar.sh` to get jar file fom framework-classes.dex (lovated in arm64-odex)

Does the method changed for **API 24** images?

@imknown could You send me the link to the **exact ROM** that You've been using?
Using my image I had problem to open system.img file (I had to convert it as I've described above) 
What tools do You use to extract and mount system.img from archives?

**Comment by imknown** [comment]
@kasptom Hi, I use [here][ROM 助手] to extract google offical `system.img` on `Windows`.
This tool is `easy-to-use` and `noob-friendly` for me. :laughing: 
[ROM 助手]: http://en.romzhushou.com/

**Comment by kasptom** [comment]
Thanks. I will have the possibility to try it for about 10 hours because then I will get to the PC with Windows :)

**Comment by testwhat** [comment]
About dex2jar, try this https://github.com/testwhat/dex2jar/releases/tag/snapshot

**Comment by kasptom** [comment]
@testwhat thanks - it works better but opening it with [jd-gui](http://jd.benow.ca/) fails for some classes, e.g TextView.class
I've got framework-classes2-dex2jar.jar. Command generates also .zip file with an error report
[framework-classes2-error.zip](https://github.com/testwhat/SmaliEx/files/422922/framework-classes2-error.zip)
[zipped framework-classes2-dex2jar](https://github.com/testwhat/SmaliEx/files/422937/framework-classes2-dex2jar.zip)

**Comment by kasptom** [comment]
@testwhat @imknown thanks for Your help. I've managed to get to the sources that I wanted :smile: 
As You suggested - I've used:
* oat2dex built like int #36 
* dex2jar from the link : https://github.com/testwhat/dex2jar/releases/tag/snapshot
* [ROM Zhushou](http://en.romzhushou.com/)

**Comment by bursoft-git** [comment]
I use Batch Apktool for proper deodexing, just put all files to _system folder and type 01 for deodexing
Full log and symlinks are stored in log_deodex.txt
For updating oat2dex.jar just put [latest version](https://drone.io/github.com/testwhat/SmaliEx/files) to BIN folder

4PDA forum http://4pda.ru/forum/index.php?showtopic=557858
Direct download link https://yadi.sk/d/h0kXdksftzdbf
