### ISSUE TITLE
Smali 2.2 beta

### ISSUE THREAD

**Issue by mfonville** [testwhat/SmaliEx#41]
Hi,

would you be able to do a build based on the latest 2.2 beta of smali ?
It can be found at https://github.com/JesusFreke/smali/tree/v2.2_WIP

its dev thinks some issues should be resolved and Nougat compatibility should work.

**Comment by testwhat** [comment]
Merged on "smali" branch. Not tested yet.

**Comment by mfonville** [comment]
Thanks.
Jesusfreke fixed some more bugs and has now beta3. Could you update once more?

**Comment by mfonville** [comment]
Thanks for the new update.
For some reason, if I try to de-odex `RemoteControlService` from Nougat Fugu, it does work with JesusFreke's tool (so calling `baksmali x`, and after that `smali a`) but `oat2dex.jar` fails :-/

**Comment by mfonville** [comment]
There have again been some updates on smali, currently it is v2.2b4, maybe you'd like to update the tool again?

**Comment by mfonville** [comment]
Do you think another update would be possible?

**Comment by mfonville** [comment]
Smali 2.2 final has been tagged
