### ISSUE TITLE
oat2dex cannot be run on read-only locations

### ISSUE THREAD

**Issue by mfonville** [testwhat/SmaliEx#6]
Often I just mount the android system image I'd like to deodex. But since this mountpoint is read-only, the script cannot be executed. Would it be possible to implement to allow reading from location X and do all write operations to another location Y?

**Comment by Aaahh** [comment]
I've done that, check out deodex app

**Comment by testwhat** [comment]
Added -o parameter. [download latest](https://github.com/testwhat/SmaliEx/blob/3ee8b5fc45a0360a73d3914c2417237ae4dd8e21/smaliex-bin/oat2dex.jar?raw=true)

Example: java -jar oat2dex.jar -o output_location app.odex boot_dex_folder

**Comment by mfonville** [comment]
Awesome, thank you!
