### ISSUE TITLE
Xperia M2 5.1.1 deodexing problem 

### ISSUE THREAD

**Issue by Gauravz007** [testwhat/SmaliEx#8]
Hi 
I am trying to deodex my stock 5.1.1 but it is failing
This was the output http://pastebin.com/hztmd4Pd
I've also tried Joeldroid tool it says Oat2Dex Conversion Failed in all apps and jar

**Comment by Gauravz007** [comment]
@testwhat here is boot.oat and system/framework https://docs.google.com/uc?authuser=0&id=0B3Kv6vLpoAA0ZE9mSF95cXFqOE0&export=download

**Comment by testwhat** [comment]
Try this https://github.com/testwhat/SmaliEx/blob/7bee4adaec9f5e28e6761bf6fd7f85fa477f6b79/smaliex-bin/oat2dex.jar

Fix: 7bee4ada

**Comment by Gauravz007** [comment]
@testwhat

This was the output 

E:\Deodex Tools\Deodex>java -jar oat2dex.jar devfw
10-31 21:30:30:551 Found  E:\Deodex Tools\Deodex\boot.oat, skip pull boot.oat
10-31 21:30:30:591 Pulling /system/framework/core-libart.jar
10-31 21:30:30:614 Pulling /system/framework/conscrypt.jar
10-31 21:30:30:638 Pulling /system/framework/okhttp.jar
10-31 21:30:30:662 Pulling /system/framework/core-junit.jar
10-31 21:30:30:687 Pulling /system/framework/bouncycastle.jar
10-31 21:30:30:711 Pulling /system/framework/ext.jar
10-31 21:30:31:001 Pulling /system/framework/framework.jar
10-31 21:30:31:024 Pulling /system/framework/telephony-common.jar
10-31 21:30:31:044 Pulling /system/framework/voip-common.jar
10-31 21:30:31:068 Pulling /system/framework/ims-common.jar
10-31 21:30:31:093 Pulling /system/framework/mms-common.jar
10-31 21:30:31:117 Pulling /system/framework/android.policy.jar
10-31 21:30:31:143 Pulling /system/framework/apache-xml.jar
10-31 21:30:31:205 Pulling /system/framework/qcmediaplayer.jar
10-31 21:30:31:243 Pulling /system/framework/org.codeaurora.Performance.jar
10-31 21:30:31:267 Pulling /system/framework/vcard.jar
10-31 21:30:31:291 Pulling /system/framework/tcmiface.jar
10-31 21:30:31:311 Pulling /system/framework/WfdCommon.jar
10-31 21:30:31:335 Pulling /system/framework/qcom.fmradio.jar
10-31 21:30:31:359 Pulling /system/framework/oem-services.jar
10-31 21:30:31:385 Pulling /system/framework/com.sonyericsson.uxp.jar
10-31 21:30:31:436 Output raw dex: E:\Deodex Tools\Deodex\odex\core-libart.dex
10-31 21:30:31:436 Output raw dex: E:\Deodex Tools\Deodex\odex\conscrypt.dex
10-31 21:30:31:451 Output raw dex: E:\Deodex Tools\Deodex\odex\okhttp.dex
10-31 21:30:31:451 Output raw dex: E:\Deodex Tools\Deodex\odex\core-junit.dex
10-31 21:30:31:467 Output raw dex: E:\Deodex Tools\Deodex\odex\bouncycastle.dex
10-31 21:30:31:467 Output raw dex: E:\Deodex Tools\Deodex\odex\ext.dex
10-31 21:30:31:482 Output raw dex: E:\Deodex Tools\Deodex\odex\framework.dex
10-31 21:30:31:498 Output raw dex: E:\Deodex Tools\Deodex\odex\framework-classes2.dex
10-31 21:30:31:498 Output raw dex: E:\Deodex Tools\Deodex\odex\telephony-common.dex
10-31 21:30:31:717 Output raw dex: E:\Deodex Tools\Deodex\odex\voip-common.dex
10-31 21:30:31:732 Output raw dex: E:\Deodex Tools\Deodex\odex\ims-common.dex
10-31 21:30:31:732 Output raw dex: E:\Deodex Tools\Deodex\odex\mms-common.dex
10-31 21:30:31:748 Output raw dex: E:\Deodex Tools\Deodex\odex\android.policy.dex
10-31 21:30:31:748 Output raw dex: E:\Deodex Tools\Deodex\odex\apache-xml.dex
10-31 21:30:31:748 Output raw dex: E:\Deodex Tools\Deodex\odex\qcmediaplayer.dex
10-31 21:30:31:748 Output raw dex: E:\Deodex Tools\Deodex\odex\org.codeaurora.Performance.dex
10-31 21:30:31:764 Output raw dex: E:\Deodex Tools\Deodex\odex\vcard.dex
10-31 21:30:31:764 Output raw dex: E:\Deodex Tools\Deodex\odex\tcmiface.dex
10-31 21:30:31:764 Output raw dex: E:\Deodex Tools\Deodex\odex\WfdCommon.dex
10-31 21:30:31:764 Output raw dex: E:\Deodex Tools\Deodex\odex\qcom.fmradio.dex
10-31 21:30:31:764 Output raw dex: E:\Deodex Tools\Deodex\odex\oem-services.dex
10-31 21:30:31:764 Output raw dex: E:\Deodex Tools\Deodex\odex\com.sonyericsson.uxp.dex
10-31 21:30:31:779 Preparing bootclasspath from E:\Deodex Tools\Deodex\odex
10-31 21:30:31:998 De-optimizing okhttp.jar
10-31 21:30:33:311 Output E:\Deodex Tools\Deodex\boot-jar-result\okhttp.jar
10-31 21:30:33:342 De-optimizing tcmiface.jar
10-31 21:30:33:358 Output E:\Deodex Tools\Deodex\boot-jar-result\tcmiface.jar
10-31 21:30:33:358 De-optimizing core-junit.jar
10-31 21:30:33:404 Output E:\Deodex Tools\Deodex\boot-jar-result\core-junit.jar
10-31 21:30:33:420 De-optimizing bouncycastle.jar
10-31 21:30:34:559 Output E:\Deodex Tools\Deodex\boot-jar-result\bouncycastle.jar
10-31 21:30:34:559 De-optimizing vcard.jar
10-31 21:30:34:700 Output E:\Deodex Tools\Deodex\boot-jar-result\vcard.jar
10-31 21:30:34:716 De-optimizing mms-common.jar
10-31 21:30:34:716 Output E:\Deodex Tools\Deodex\boot-jar-result\mms-common.jar
10-31 21:30:34:731 De-optimizing conscrypt.jar
10-31 21:30:34:997 Output E:\Deodex Tools\Deodex\boot-jar-result\conscrypt.jar
10-31 21:30:35:012 De-optimizing telephony-common.jar
10-31 21:30:36:701 Output E:\Deodex Tools\Deodex\boot-jar-result\telephony-common.jar
10-31 21:30:36:701 De-optimizing WfdCommon.jar
10-31 21:30:36:764 Output E:\Deodex Tools\Deodex\boot-jar-result\WfdCommon.jar
10-31 21:30:36:779 De-optimizing framework.jar
10-31 21:30:44:999 De-optimizing framework.jar part-2
10-31 21:30:47:265 Output E:\Deodex Tools\Deodex\boot-jar-result\framework.jar
10-31 21:30:47:265 De-optimizing oem-services.jar
10-31 21:30:47:265 Output E:\Deodex Tools\Deodex\boot-jar-result\oem-services.jar
10-31 21:30:47:265 De-optimizing qcom.fmradio.jar
10-31 21:30:47:296 Output E:\Deodex Tools\Deodex\boot-jar-result\qcom.fmradio.jar
10-31 21:30:47:296 De-optimizing apache-xml.jar
10-31 21:30:47:874 Output E:\Deodex Tools\Deodex\boot-jar-result\apache-xml.jar
10-31 21:30:47:874 De-optimizing org.codeaurora.Performance.jar
10-31 21:30:47:874 Output E:\Deodex Tools\Deodex\boot-jar-result\org.codeaurora.Performance.jar
10-31 21:30:47:890 De-optimizing ext.jar
10-31 21:30:48:921 Output E:\Deodex Tools\Deodex\boot-jar-result\ext.jar
10-31 21:30:48:999 De-optimizing voip-common.jar
10-31 21:30:49:062 Output E:\Deodex Tools\Deodex\boot-jar-result\voip-common.jar
10-31 21:30:49:062 De-optimizing core-libart.jar
10-31 21:30:50:437 Output E:\Deodex Tools\Deodex\boot-jar-result\core-libart.jar
10-31 21:30:50:437 De-optimizing ims-common.jar
10-31 21:30:50:468 Output E:\Deodex Tools\Deodex\boot-jar-result\ims-common.jar
10-31 21:30:50:484 De-optimizing android.policy.jar
10-31 21:30:50:593 Output E:\Deodex Tools\Deodex\boot-jar-result\android.policy.jar
10-31 21:30:50:609 De-optimizing qcmediaplayer.jar
10-31 21:30:50:609 Output E:\Deodex Tools\Deodex\boot-jar-result\qcmediaplayer.jar
10-31 21:30:50:640 De-optimizing com.sonyericsson.uxp.jar
10-31 21:30:50:656 Output E:\Deodex Tools\Deodex\boot-jar-result\com.sonyericsson.uxp.jar
10-31 21:30:50:705 Pulling /system/framework/arm/am.odex
10-31 21:30:50:740 Pulling /system/framework/am.jar
10-31 21:30:50:765 Preparing bootclasspath from E:\Deodex Tools\Deodex\boot-jar-result
10-31 21:30:50:952 java.lang.ArrayIndexOutOfBoundsException: 1618214710
        at org.jf.dexlib2.dexbacked.BaseDexReader.readUleb128(BaseDexReader.java:101)
        at org.jf.dexlib2.dexbacked.BaseDexReader.readSmallUleb128(BaseDexReader.java:92)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:86)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:135)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:131)
        at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
        at org.jf.dexlib2.analysis.ClassPath.addDex(ClassPath.java:113)
        at org.rh.smaliex.OatUtil.convertToDexJar(OatUtil.java:343)
        at org.rh.smaliex.DeodexFrameworkFromDevice.generateNonBootFrameworkJar(DeodexFrameworkFromDevice.java:103)
        at org.rh.smaliex.DeodexFrameworkFromDevice.deOptimizeFramework(DeodexFrameworkFromDevice.java:68)
        at org.rh.smaliex.DeodexFrameworkFromDevice$1.run(DeodexFrameworkFromDevice.java:53)
        at org.rh.smaliex.AdbUtil$3.deviceConnected(AdbUtil.java:174)
        at com.android.ddmlib.AndroidDebugBridge.deviceConnected(AndroidDebugBridge.java:657)
        at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:341)
        at com.android.ddmlib.DeviceMonitor.processIncomingDeviceData(DeviceMonitor.java:282)
        at com.android.ddmlib.DeviceMonitor.deviceMonitorLoop(DeviceMonitor.java:157)
        at com.android.ddmlib.DeviceMonitor.access$000(DeviceMonitor.java:34)
        at com.android.ddmlib.DeviceMonitor$1.run(DeviceMonitor.java:65)

**Comment by testwhat** [comment]
It looks the output is the same as previous.
The old oat2dex.jar is 1,309,177 bytes. The new is 1,309,209 bytes. Please check if using the new jar.

Below output is generated from the system image of OMNI-EagleM2 without error:
https://drive.google.com/file/d/0B2eqQAIyvIz_VGhmUVM3OHFhbnc/view

**Comment by Gauravz007** [comment]
@testwhat I've verified the oat2dex.jar its new one only And I am Deodexing stock ROM.
Other LP based roms didn't cause any errors 
Here is the boot.oat and other files if you wanna check https://docs.google.com/uc?authuser=0&id=0B3Kv6vLpoAA0ZE9mSF95cXFqOE0&export=download

**Comment by Gauravz007** [comment]
@testwhat problem solved Thanks :)
http://forum.xda-developers.com/xperia-m2/development/stock-xperia-m2-deodex-patch-t3243891/post63718822#post63718822
